1 explicit pages:
  config/english/config_en.prc

2 implicit pages:
  /c/Panda3D-1.8.1/etc/Config.prc
  /c/Panda3D-1.8.1/etc/Confauto.prc

serverVersion:  sv-1.0.0
PAccount: accountServer from launcher:  
PAccount: default accountServer:  https://pirates.go.com
Initializing quest ladders...
Traceback (most recent call last):
  File "C:\Panda3D-1.8.1\python\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Panda3D-1.8.1\python\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\Tyler\Desktop\POTCOR-src\pirates\piratesbase\PiratesStart.py", line 62, in <module>
    cr = PiratesClientRepository.PiratesClientRepository(serverVersion, launcher)
  File "pirates\distributed\PiratesClientRepository.py", line 113, in __init__
    self.accept('connectionIssue', self.loadingScreen.hide())
  File "C:\Panda3D-1.8.1\direct\showbase\DirectObject.py", line 25, in accept
    return messenger.accept(event, self, method, extraArgs, 1)
  File "C:\Panda3D-1.8.1\direct\showbase\Messenger.py", line 202, in accept
    (safeRepr(method), safeRepr(extraArgs)))
AssertionError: method not callable in accept (ignoring): None []
